### ISSUE TITLE
What if I press back button after successful trannsaction?

### ISSUE THREAD

**Issue by ashutoshkrris** [amljs/paytm-node.js#1]
If the transaction is successful, the response page is rendered.
If then, I press the back button, I am able to make the transaction again..but technically, it should show error..

**Comment by amljs** [comment]
hi, @ashutoshkrris there are ways you can prevent it like disabling the back button or removing the response cache so that if a user tries to hit back a "page expired" warning will show.

**Comment by amalj07** [comment]
hi, @ashutoshkrris there are ways it can be prevented by disabling the back button or clearing the response cache so that if a user hit back button a "page expired" warning will show.

**Comment by amalj07** [comment]
when i tested the response is rendered but the transaction is not happening again. the transaction id I got after hitting refresh or going back were same.

**Comment by ashutoshkrris** [comment]
Yes, I noticed right now that the transaction is not happening. 
Anyways, I shall disable the back button or clear the response cache.
Thanks for the help! @amljs

**Comment by amalj07** [comment]
@ashutoshkrris I think it's better to give them a warning if they try to go back or hit refresh. It can be done by detecting `onbeforeunload ` and handle that appropriately and give them a warning.

Check these links, it might help

https://stackoverflow.com/a/837870/13865027
https://stackoverflow.com/questions/17966761/restrict-user-to-go-back-after-payment-has-been-done
https://stackoverflow.com/questions/19558038/how-to-restrict-the-user-not-go-to-previous-pages-by-clicking-the-browsers-back
https://stackoverflow.com/a/12381610/13865027

**Comment by ashutoshkrris** [comment]
Thanks for the help !! @amljs
